version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - deploy.env
    # environment:
    #   - VITE_APP_NAME=$VITE_APP_NAME
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT